services:
- postgresql
before_script:
- psql -c 'create database teste;' -U postgres
- psql -U postgres -d teste -f src/script/database/create_tables.sql
- psql -U postgres -d teste -f src/script/database/fill_tables.sql
- cd src/Tads2017
language: java
jdk:
- oraclejdk8
script: mvn clean verify -DskipTests=false -DskipITs=false -DskipSTs=false
deploy:
  provider: heroku
  api_key:
    secure: u4Jxxr9XUF3NZ5l1usXCFC0p2F6vjaHSEf84Ew2R1Z9Su51zKQqeJMNmj91sMUH15fgQQkcdbwZLP9K7RBZ+cXdqPFvdspmNlfKAYVuyacvyRyfkiwrwtgSrK1S5+WJmQo7CaGWYWjzDat08YIJgTt4miT7yUVJsxkacBQO+xAs9KzPMEKUyIbVk+y9va1aM44+NFusS892QPj1YTbnun8ahK7hFW7rHLwPf2Nlv5zUbWPnnxp2F8g5JL6hEz0wovMgw0NBhlxioIP9KVJ9qUREdMz12Wh2i0T3HgxNAxfuFAvJN+y5bFxk4F4c9w3kCOOBdaSiSzKu6/jpqzyJP9h/syw8vrHXiIkwowv1ViBpFFW5JLxymCpP+ty01hUY00594aiDwF+5W2okJ/qwDNVOmRx+k2M6o6Q3s7CsLyGk8Z4bVVU7QHraWjolzKnYJPEZdyO031CxDNQRKsjqdkNC+6hh9cg3chBeQ7AC3SmPhvP//WeiTpusBjxmEK2VCU4s+Xvr8U9BmVa6SH6EL7II/3WGisGs3SgPb7eTLzk2ryV2U8f+ZHUiqKpSeEUtNK6GrkiJwIp1l1AVUM92VFCz2D21I13pj9V3IDeVHMUXIjIMqznClB/GiPK5wUOxhRds8gKClD76CjwURsuqDgmH+Ynk0p7oA1k4sU+jMxSA=
