services:
- postgresql
before_script:
 - psql -c 'create database teste;' -U postgres
 - psql -U postgres -d teste -f script/database/create_tables.sql
 - psql -U postgres -d teste -f script/database/fill_tables.sql
 - cd src/Tads2017
# - ls
language: java
jdk:
  - oraclejdk8
script: mvn clean verify -DskipTests=false -DskipITs=false -DskipSTs=false
